### ISSUE TITLE
Pre-made CSS for using Metropolis webfonts?

### ISSUE THREAD

**Issue by hartwork** [chrismsimpson/Metropolis#36]
Hi!

This font looks pretty cool — thanks for sharing it under a free license!

I found web font builds of Metropolis in folder [`Fonts/Webfonts`](https://github.com/chrismsimpson/Metropolis/tree/master/Fonts/Webfonts). I wonder if there are plans to make a CSS file for when someone would serve the font files and a CSS file from some assets web folder, say a structure like this:
```
static/
  css/
    metropolis.css
  fonts/
    metrolis/
      woff/
        *.woff
      woff2/
        *.woff2
```
Are there plans to provide a ready-to-use CSS file for a case like that?

Thanks and best, Sebastian

**Comment by chrismsimpson** [comment]
Not a bad idea. I'd likely put it in `Fonts/CSS`, so it's a little dummy proof and I don't have to change the overall structure of the project. I'll keep you posted.

**Comment by ramiroaisen** [comment]
Here is the css if you wanna add it... for the ones using the font from here just place it in the same directory of the fonts (woff2)

```css
@font-face {
    font-family: "Metropolis";
    font-weight: 100;
    font-style: normal;
    font-display: swap;
    src: url("./Metropolis-Thin.woff2") format("woff2");
}

@font-face {
    font-family: "Metropolis";
    font-weight: 100;
    font-style: italic;
    font-display: swap;
    src: url("./Metropolis-ThinItalic.woff2") format("woff2");
}

@font-face {
    font-family: "Metropolis";
    font-weight: 200;
    font-style: normal;
    font-display: swap;
    src: url("./Metropolis-ExtraLight.woff2") format("woff2");
}

@font-face {
    font-family: "Metropolis";
    font-weight: 200;
    font-style: italic;
    font-display: swap;
    src: url("./Metropolis-ExtraLightItalic.woff2") format("woff2");
}

@font-face {
    font-family: "Metropolis";
    font-weight: 300;
    font-style: normal;
    font-display: swap;
    src: url("./Metropolis-Light.woff2") format("woff2");
}

@font-face {
    font-family: "Metropolis";
    font-weight: 300;
    font-style: italic;
    font-display: swap;
    src: url("./Metropolis-LightItalic.woff2") format("woff2");
}

@font-face {
    font-family: "Metropolis";
    font-weight: 400;
    font-style: normal;
    font-display: swap;
    src: url("./Metropolis-Regular.woff2") format("woff2");
}

@font-face {
    font-family: "Metropolis";
    font-weight: 400;
    font-style: italic;
    font-display: swap;
    src: url("./Metropolis-RegularItalic.woff2") format("woff2");
}

@font-face {
    font-family: "Metropolis";
    font-weight: 500;
    font-style: normal;
    font-display: swap;
    src: url("./Metropolis-Medium.woff2") format("woff2");
}

@font-face {
    font-family: "Metropolis";
    font-weight: 500;
    font-style: italic;
    font-display: swap;
    src: url("./Metropolis-MediumItalic.woff2") format("woff2");
}

@font-face {
    font-family: "Metropolis";
    font-weight: 600;
    font-style: normal;
    font-display: swap;
    src: url("./Metropolis-SemiBold.woff2") format("woff2");
}

@font-face {
    font-family: "Metropolis";
    font-weight: 600;
    font-style: italic;
    font-display: swap;
    src: url("./Metropolis-SemiBoldItalic.woff2") format("woff2");
}

@font-face {
    font-family: "Metropolis";
    font-weight: 700;
    font-style: normal;
    font-display: swap;
    src: url("./Metropolis-Bold.woff2") format("woff2");
}

@font-face {
    font-family: "Metropolis";
    font-weight: 700;
    font-style: italic;
    font-display: swap;
    src: url("./Metropolis-BoldItalic.woff2") format("woff2");
}

@font-face {
    font-family: "Metropolis";
    font-weight: 800;
    font-style: normal;
    font-display: swap;
    src: url("./Metropolis-ExtraBold.woff2") format("woff2");
}

@font-face {
    font-family: "Metropolis";
    font-weight: 800;
    font-style: italic;
    font-display: swap;
    src: url("./Metropolis-ExtraBoldItalic.woff2") format("woff2");
}

@font-face {
    font-family: "Metropolis";
    font-weight: 900;
    font-style: normal;
    font-display: swap;
    src: url("./Metropolis-Black.woff2") format("woff2");
}

@font-face {
    font-family: "Metropolis";
    font-weight: 900;
    font-style: italic;
    font-display: swap;
    src: url("./Metropolis-BlackItalic.woff2") format("woff2");
}
```
